on:
  push:
    branches-ignore:
    - master

name: CI
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Docker Login
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: nicoCode97/test-gha:${{ github.sha }}
